export default function HowItWorksPage() {
  const steps = [
    {
      step: 1,
      title: 'Ask a Question',
      desc: 'Type a legal question in plain English — e.g. "What is the right to privacy?"',
    },
    {
      step: 2,
      title: 'Retrieve Provisions',
      desc: 'Our hybrid search engine (BM25 + term proximity + title boost) finds the most relevant constitutional articles.',
    },
    {
      step: 3,
      title: 'LLM Answer (optional)',
      desc: 'Toggle LLM on to get a citation-backed answer generated by Gemma 3:1b, grounded in the retrieved articles.',
    },
    {
      step: 4,
      title: 'Explore Results',
      desc: 'Expand each article card to see the full provision text and related articles.',
    },
  ];

  return (
    <div className="max-w-2xl mx-auto mt-16 px-4">
      <h1 className="text-3xl font-bold text-gray-900 mb-8">How It Works</h1>
      <div className="space-y-6">
        {steps.map(({ step, title, desc }) => (
          <div key={step} className="flex gap-4">
            <div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center shrink-0">
              <span className="text-sm font-bold text-blue-600">{step}</span>
            </div>
            <div>
              <h2 className="text-lg font-semibold text-gray-900">{title}</h2>
              <p className="text-sm text-gray-600 mt-1">{desc}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
